### ISSUE TITLE
Burger menu

### ISSUE THREAD

**Issue by VictorNov** [Training-Sasha/w-wave#24]
Пример кода на JS

``` js
/*=============== SHOW MENU ===============*/
const navMenu = document.getElementById('nav-menu'), // this is burger menu itself
      navToggle = document.getElementById('nav-toggle'), // this is burger button
      navClose = document.getElementById('nav-close') // this is close button inside menu

/*===== MENU SHOW =====*/
/* Validate if constant exists */
if(navToggle){
    navToggle.addEventListener('click', () =>{
        navMenu.classList.add('show-menu') // on click add class 'show-menu' to menu
    })
}

/*===== MENU HIDDEN =====*/
/* Validate if constant exists */
if(navClose){
    navClose.addEventListener('click', () =>{
        navMenu.classList.remove('show-menu') // on click close button remove class 'show-menu' from menu
    })
}

/*=============== REMOVE MENU MOBILE ===============*/
const navLink = document.querySelectorAll('.nav__link')

function linkAction(){
    const navMenu = document.getElementById('nav-menu')
    // When we click on each nav__link, we remove the show-menu class
    navMenu.classList.remove('show-menu')
}
navLink.forEach(n => n.addEventListener('click', linkAction))
```

``` css
@media screen and (max-width: 767px){
  .nav__menu{
    position: fixed;
    inset: 0; // to take full screen width/height
    transform: translateY(-150%); // initial position is outside of screen
    transition: .4s;
  }
}

/* Show menu */
.show-menu{
  transform: translateY(0); // move menu back to screen
}
```

В примере меню появится сверху, но меняя начальные значения можно применить другие эффекты появления

![Image](https://github.com/Training-Sasha/w-wave/assets/94706594/79315c37-4eb5-42ff-8977-85e8d0d2cd7d)
![Image](https://github.com/Training-Sasha/w-wave/assets/94706594/fa6dc8e2-20ff-45e7-8039-7a4ec69d23ec)
